import NavBar from "@/components/NavBar";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
  image: "dish.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-screen-2xl m-auto  min-h-screen w-screen bg-white">
          <NavBar />
          <div className="pt-20 p-10 h-100 bg-gray-100">{children}</div>
        </main>
      </body>
    </html>
  );
}
