import NavBar from "@/app/[locale]/components/NavBar";

import "./globals.css";
import { Inter } from "next/font/google";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Contact list",
  description: "Generated by create next app",
  image: "dish.png",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const locale = useLocale();
  if (params.locale !== locale) {
    notFound();
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-screen-2xl m-auto  min-h-screen w-screen bg-white">
          <NavBar />
          <div className="pt-20 p-10 h-100 bg-gray-100">{children}</div>
        </main>
      </body>
    </html>
  );
}
